name: Basic cicd-main..

on:
  workflow_dispatch:
  push:
    #paths:
    # - 'ownproject/**' 
     branches:
      - main


jobs:
  deploy:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: ownproject

    steps:
      # Checkout code
      - name: checkout code
        uses: actions/checkout@v4

      # del the container
      - name: Delete old contailer
        #run: docker ps -aq --filter "name=^prodcont-" | xargs -r docker rm -f
        run: docker rm -f $(docker ps -aq --filter "name=prodcont-") || true

      # Build docker
      - name: Build docker file
        run: docker build -t prodapp:${{github.run_number}} .

      # debug
      - name: debugit
        run: |
          pwd
          ls -la
          find . -name "requirements.txt"

      # Run container
      - name: Run karo
        run: docker run -d -p 5000:5000 --name prodcont-${{github.run_number}} prodapp:${{github.run_number}}
        
 
